### ISSUE TITLE
OSError: [Errno 99] Address not available

### ISSUE THREAD

**Issue by dalcon007** [robsonke/hassio-addons#2]
Hi,

I seem to be getting the following error, running Home Assistant OS 2021.10.2 on a VM.

```
[23:20:27] INFO: Read all configuration settings
[23:20:28] INFO: Start the amcrest2mqtt.py
10/10/2021 03:20:29 [INFO] App Version: 1.0.9
10/10/2021 03:20:29 [INFO] Fetching camera details...
10/10/2021 03:20:32 [INFO] Device type: AD410
10/10/2021 03:20:32 [INFO] Serial number: *******************
10/10/2021 03:20:32 [INFO] Software version: build:2021-02-20
10/10/2021 03:20:32 [INFO] Device name: Front Door
Traceback (most recent call last):
  File "/app/amcrest2mqtt.py", line 214, in <module>
    mqtt_client.connect(mqtt_host, port=mqtt_port)
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "/usr/local/lib/python3.9/site-packages/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/local/lib/python3.9/socket.py", line 843, in create_connection
    raise err
  File "/usr/local/lib/python3.9/socket.py", line 831, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Address not available
```
I've double checked all addresses, it can possibly be a connection issue? But it is fetching the correct serial number and device name, so this is confusing. Any help is appreciated.

Thank you

**Comment by robsonke** [comment]
It looks like your mqtt connection is failing. Are you sure that addon (if you run it as an addon of course) is up?

**Comment by dalcon007** [comment]
Yes, it is running. However in the logs I see
`Socket error on client <unknown>, disconnecting.`

I am not sure what I'm missing!

**Comment by robsonke** [comment]
Then I'd say your settings are incorrect. Since it can't find the address it tries to connect to.

**Comment by MarcAnt1** [comment]
Change your mqtt adsress to the actual IP insted of "localhost"

**Comment by robsonke** [comment]
Thanks for the tip Marc, closing this one
